version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: biroul-postgres
    environment:
      POSTGRES_DB: biroul
      POSTGRES_USER: biroul_user
      POSTGRES_PASSWORD: biroul_pass
    ports:
      - "5432:5432"
    volumes:
      - biroul_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: biroul-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@biroul.ro
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  biroul_pgdata:
